# Generated by Django 5.0.6 on 2025-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='umbral_stock_bajo',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
